worker_app: synapse.app.client_reader

# The replication listener on the synapse to talk to.
worker_replication_host: synapse
worker_replication_port: 9092
worker_replication_http_port: 9093

worker_listeners:
  - type: http
    tls: false
    port: 8008
    resources:
      - names:
        - client
        compress: false
