worker_app: synapse.app.federation_sender

send_federation: True

# The replication listener on the synapse to talk to.
worker_replication_host: synapse
worker_replication_port: 9092
worker_replication_http_port: 9093
